apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: mongodb  
  labels:   
    app: mongodb  
spec:  
  replicas: 1  
  selector:  
    matchLabels:  
      app: mongodb  
  template:  
    metadata:  
      labels:  
        app: mongodb  
    spec:  
      containers:  
        - name: mongodb  
          image: mongo:latest  
          imagePullPolicy: IfNotPresent
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: root
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-pass
                key: password  
          ports:  
           - containerPort: 27017  
          volumeMounts:  
           - mountPath: "/data/db"  
             name: task-pv-storage  
      volumes:  
        - name: task-pv-storage  
          persistentVolumeClaim:  
           claimName: task-pv-claim 
---
kind: PersistentVolumeClaim  
apiVersion: v1  
metadata:  
  name: task-pv-claim  
spec:  
  storageClassName: manual  
  accessModes:  
    - ReadWriteOnce  
  resources:  
    requests:  
      storage: 2Gi
---
kind: PersistentVolume  
apiVersion: v1  
metadata:  
  name: task-pv-volume  
  labels:  
    type: local  
spec:  
  storageClassName: manual  
  capacity:  
    storage: 2Gi  
  accessModes:  
    - ReadWriteOnce  
  hostPath:  
    path: "/home/Task"
